// GENERATO DA scripts/sitemap.mjs — non modificare a mano.
// Rigenera con: npm run seo
//
// Solo i metadati dei post: titolo, descrizione e data servono a costruire i tag SEO e il
// JSON-LD di ogni articolo senza tirarsi dietro i 292 KB di testo di blogPosts.ts.

export type BlogMeta = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  /** Data come mostrata in pagina, es. "11 novembre 2025". */
  date: string;
  /** Stessa data in formato ISO per i dati strutturati; null se non interpretabile. */
  iso: string | null;
  /** Immagine di copertina, per l'anteprima social e i dati strutturati. */
  img: string;
};

export const BLOG_INDEX: BlogMeta[] = [
  { slug: 'come-diventare-coach-professionista-in-italia', title: 'Come diventare coach professionista in Italia: la guida completa', excerpt: 'Cosa serve davvero per diventare coach: formazione accreditata ICF, ore di pratica, mentor coaching e credenziale. Passi, tempi, costi e come scegliere la scuola.', category: 'Diventare coach', date: '11 novembre 2025', iso: '2025-11-11', img: '/blog/come-diventare-coach-professionista-in-italia.jpg' },
  { slug: 'quanto-guadagna-e-quanto-costa-diventare-coach-in-italia', title: 'Quanto guadagna e quanto costa diventare coach in Italia', excerpt: 'Tariffe, redditi e costi reali della professione di coach in Italia: quanto si guadagna, quanto costa la formazione e quando conviene davvero.', category: 'Professione coach', date: '8 novembre 2025', iso: '2025-11-08', img: '/blog/quanto-guadagna-e-quanto-costa-diventare-coach-in-italia.jpg' },
  { slug: 'credenziali-icf-cosa-sono-a-cosa-servono-e-come-ottenerle', title: 'Credenziali ICF: cosa sono, a cosa servono e come ottenerle', excerpt: 'Una guida alle credenziali della International Coaching Federation: cosa sono, i tre livelli ACC, PCC e MCC, i requisiti per ottenerle e come prepararsi al meglio.', category: 'Credenziali ICF', date: '28 ottobre 2025', iso: '2025-10-28', img: '/blog/credenziali-icf-cosa-sono-a-cosa-servono-e-come-ottenerle.png' },
  { slug: 'come-scegliere-una-scuola-di-coaching-accreditata-icf', title: 'Come scegliere una scuola di coaching accreditata ICF', excerpt: 'Accreditamento, trainer, pratica supervisionata, metodo: i criteri concreti per scegliere una scuola di coaching seria ed evitare i percorsi “lampo”.', category: 'Diventare coach', date: '4 novembre 2025', iso: '2025-11-04', img: '/blog/come-scegliere-una-scuola-di-coaching-accreditata-icf.jpg' },
  { slug: 'rinnovo-credenziale-icf-cce-e-mentor-coaching', title: 'Rinnovo della credenziale ICF: come funziona (CCE e mentor coaching)', excerpt: 'Le credenziali ICF si rinnovano ogni 3 anni con 40 CCE. Cosa contano, quante ore di mentor coaching servono e come maturarle in gruppo o individuale.', category: 'Credenziali ICF', date: '1 novembre 2025', iso: '2025-11-01', img: '/blog/rinnovo-credenziale-icf-cce-e-mentor-coaching.jpg' },
  { slug: 'serendipita-e-coaching-il-segreto-che-arriva-per-caso', title: 'Serendipità e Coaching – Il segreto che arriva per caso', excerpt: 'La serendipità non è semplice fortuna, ma l\'incontro tra il caso e una mente preparata. Una riflessione su come questa capacità di vedere l\'opportunità nell\'imprevisto assomigli al coaching.', category: 'Metodo e pratica', date: '25 ottobre 2025', iso: '2025-10-25', img: '/blog/serendipita-e-coaching-il-segreto-che-arriva-per-caso.jpg' },
  { slug: 'rischi-e-vantaggi-dellesposizione-mediatica', title: 'Rischi e vantaggi dell’esposizione mediatica', excerpt: 'L’invito a un format televisivo diventa lo spunto per riflettere sul rapporto tra notorietà e professione. Quando la visibilità è un acceleratore di carriera e quando invece rischia di diventare un freno.', category: 'Professione coach', date: '26 agosto 2025', iso: '2025-08-26', img: '/blog/rischi-e-vantaggi-dellesposizione-mediatica.png' },
  { slug: 'il-potere-della-voce', title: 'Il potere della voce', excerpt: 'La voce è il nostro principale mezzo per esprimere le emozioni e influenza chi ci ascolta. Perché per un coach imparare a usarla con consapevolezza può fare la differenza.', category: 'Metodo e pratica', date: '18 ottobre 2025', iso: '2025-10-18', img: '/blog/il-potere-della-voce.jpg' },
  { slug: 'liberi-e-associati', title: 'Liberi e associati', excerpt: 'Un coach vive tra due spinte opposte: l\'individuazione professionale e il bisogno di appartenenza. Una riflessione sul valore del confronto con i colleghi e dell\'attività associativa.', category: 'Professione coach', date: '23 agosto 2025', iso: '2025-08-23', img: '/blog/liberi-e-associati.jpg' },
  { slug: 'il-modello-della-realta', title: 'Il modello della realtà', excerpt: 'Come coach il nostro primo compito è aiutare il cliente a riconoscere il “pensiero rigido” e a rendere flessibile il proprio modello di realtà. Una riflessione sulla competenza ICF “Genera Consapevolezza”.', category: 'Metodo e pratica', date: '27 settembre 2025', iso: '2025-09-27', img: '/blog/il-modello-della-realta.jpeg' },
  { slug: 'ego-mon-amour', title: 'Ego mon amour', excerpt: 'L\'ego è il sé che costruiamo, spesso rigido e difensivo. Lavorare sul nostro ego è fondamentale per evolvere, cambiare idea e tornare alla nostra vera natura.', category: 'Crescita personale', date: '7 ottobre 2025', iso: '2025-10-07', img: '/blog/ego-mon-amour.jpg' },
  { slug: 'creativita-e-coaching', title: 'Creatività e Coaching', excerpt: 'Essere creativi significa vivere ogni esperienza consapevoli di poter scegliere come viverla. Come il coaching aiuta a passare da una dimensione reattiva a una creativa.', category: 'Metodo e pratica', date: '19 agosto 2025', iso: '2025-08-19', img: '/blog/creativita-e-coaching.jpg' },
  { slug: 'valori-e-comportamenti', title: 'Valori e comportamenti', excerpt: 'I valori sono la bussola che guida le nostre scelte e sono legati al nostro senso di sé. Perché le sessioni di coaching incentrate sui valori ci aiutano a conoscerci meglio.', category: 'Crescita personale', date: '30 settembre 2025', iso: '2025-09-30', img: '/blog/valori-e-comportamenti.jpg' },
  { slug: 'perche-il-coaching-e-efficace', title: 'Perché, il Coaching è efficace?', excerpt: 'Cosa rende davvero efficace il coaching? Dalla lista \"SACRA\" ai fattori come partnership ed effetto placebo, un viaggio tra prove scientifiche e dati di sessione.', category: 'Metodo e pratica', date: '12 agosto 2025', iso: '2025-08-12', img: '/blog/perche-il-coaching-e-efficace.jpg' },
  { slug: 'in-nome-del-coaching', title: 'In nome del Coaching…', excerpt: 'Con la parola \"coaching\" si indicano attività molto diverse tra loro. Una riflessione sul significato del termine e sull\'utilità (e i limiti) di segmentarlo in mille definizioni.', category: 'Professione coach', date: '16 agosto 2025', iso: '2025-08-16', img: '/blog/in-nome-del-coaching.jpg' },
  { slug: 'coachable-o-uncoachable-questo-e-il-problema', title: 'Coachable o Uncoachable… Questo è il problema.', excerpt: 'Il coaching non è per tutti: ha senso solo con un cliente che desidera cambiare e si assume la responsabilità dei propri risultati. Come riconoscere chi è \"coachable\".', category: 'Metodo e pratica', date: '9 agosto 2025', iso: '2025-08-09', img: '/blog/coachable-o-uncoachable-questo-e-il-problema.jpg' },
  { slug: 'grande-persona-grande-coach', title: 'Grande persona, grande Coach', excerpt: 'Non basta avere un figlio per diventare bravi genitori, né fare un corso per essere un buon coach. Perché la crescita personale è il cuore della professione.', category: 'Professione coach', date: '2 agosto 2025', iso: '2025-08-02', img: '/blog/grande-persona-grande-coach.jpg' },
  { slug: 'pane-e-coaching', title: 'Pane e Coaching', excerpt: 'Un coach affamato porta con sé il conflitto d\'interessi. Perché servire davvero il cliente richiede libertà dal bisogno di denaro, attenzione e riconoscimento.', category: 'Metodo e pratica', date: '26 luglio 2025', iso: '2025-07-26', img: '/blog/pane-e-coaching.jpg' },
  { slug: 'dal-sogno-al-progetto-essere-il-motore-del-proprio-cambiamento', title: 'Dal sogno al progetto – I passi per il cambiamento', excerpt: 'Un esercizio di visualizzazione per trasformare i sogni in progetti: dai cassetti in cui i sogni invecchiano ai cappelli del pensiero, fino alle scarpe che rappresentano i passi da compiere.', category: 'Crescita personale', date: '23 settembre 2025', iso: '2025-09-23', img: '/blog/dal-sogno-al-progetto-essere-il-motore-del-proprio-cambiamento.jpg' },
  { slug: 'errori-comuni-coaching', title: '10 errori comuni del “NON Coach”', excerpt: 'La paura dell\'errore è nemica del coaching. I dieci errori più comuni di chi crede di fare il coach ma finisce nel \"non coaching\".', category: 'Metodo e pratica', date: '22 luglio 2025', iso: '2025-07-22', img: '/blog/errori-comuni-coaching.jpg' },
  { slug: 'non-aprite-quella-porta', title: '(Non) aprite quella porta', excerpt: 'Dietro la porta chiusa che tutti custodiamo dentro di noi si nasconde spesso un dolore. Una riflessione su come attraversare quel vuoto ci renda più autentici e in connessione con gli altri.', category: 'Crescita personale', date: '20 settembre 2025', iso: '2025-09-20', img: '/blog/non-aprite-quella-porta.jpg' },
  { slug: 'domande-potenti-coaching', title: 'Powerful Questions - Le domande potenti', excerpt: 'Cosa rende davvero potente una domanda di coaching, e perché forse sarebbe più corretto parlare di risposte e dialoghi potenti.', category: 'Metodo e pratica', date: '12 luglio 2025', iso: '2025-07-12', img: '/blog/domande-potenti-coaching.jpg' },
  { slug: 'un-coach-di-successo', title: 'Un vero coach di successo…', excerpt: 'Attraverso la storia (di fantasia) di John Red, sedicente coach di successo, le sette \"regole\" con cui i falsi guru costruiscono la loro credibilità.', category: 'Professione coach', date: '29 luglio 2025', iso: '2025-07-29', img: '/blog/un-coach-di-successo.jpg' },
  { slug: 'coaching-alieno', title: 'Il Coaching è un alieno?', excerpt: 'Una riflessione sul coaching come cultura ancora estranea al quotidiano, fatta di ascolto, fiducia e presenza, e su chi sono davvero i coach.', category: 'Metodo e pratica', date: '8 luglio 2025', iso: '2025-07-08', img: '/blog/coaching-alieno.jpg' },
  { slug: 'tenere-a-mente-il-corpo', title: 'Tenere a mente il corpo', excerpt: 'Mente e corpo sono due facce della stessa medaglia: le sensazioni fisiche precedono l\'azione consapevole. Come l\'ascolto del corpo e del respiro influenza le nostre scelte.', category: 'Intelligenza emotiva', date: '14 ottobre 2025', iso: '2025-10-14', img: '/blog/tenere-a-mente-il-corpo.jpg' },
  { slug: 'coach-creativo', title: 'Coach creativo o reattivo?', excerpt: 'Come passare, da persone e da coach, da una dimensione reattiva a una creativa. Partnership, empowerment e orientamento ai risultati sono gli ingredienti che liberano la capacità creativa del cliente.', category: 'Metodo e pratica', date: '24 giugno 2025', iso: '2025-06-24', img: '/blog/coach-creativo.jpg' },
  { slug: 'il-bello-delle-emozioni', title: 'Il bello delle emozioni', excerpt: 'Arte, bellezza ed emozioni nascono nel cervello e guidano il nostro apprendimento. Modellare consapevolmente la nostra mente è l\'essenza dell\'intelligenza emotiva.', category: 'Intelligenza emotiva', date: '11 ottobre 2025', iso: '2025-10-11', img: '/blog/il-bello-delle-emozioni.jpg' },
  { slug: 'coaching-what-else', title: 'Coaching, What Else?', excerpt: 'Executive, Business, Corporate, Life, Sport: una guida ai tanti nomi del coaching e a perché, alla fine, l\'essenza resta una sola.', category: 'Professione coach', date: '19 luglio 2025', iso: '2025-07-19', img: '/blog/coaching-what-else.jpg' },
  { slug: 'mindset-acceleranti-e-mindset-limitanti', title: 'Mindset acceleranti e mindset limitanti', excerpt: 'Mentalità statica o di crescita: secondo Carol Dweck ciò che pensiamo di noi determina i nostri successi. Come il lavoro del coach può aiutare a trasformare un mindset limitante in uno accelerante.', category: 'Crescita personale', date: '16 settembre 2025', iso: '2025-09-16', img: '/blog/mindset-acceleranti-e-mindset-limitanti.jpg' },
  { slug: 'non-ce-punto-di-saturazione-nella-formazione', title: 'Non c’è punto di saturazione nella formazione', excerpt: 'Non esiste successo, professionale o personale, senza il desiderio di imparare e crescere. Una riflessione sul valore della formazione continua e della cultura dell\'apprendimento.', category: 'Diventare coach', date: '21 ottobre 2025', iso: '2025-10-21', img: '/blog/non-ce-punto-di-saturazione-nella-formazione.jpg' },
  { slug: 'leadership-personale-il-potere-di-cambiare', title: 'Leadership personale: il potere di cambiare', excerpt: 'Conoscere e saper trasformare se stessi è la base per sviluppare una potente leadership personale ed esprimere al meglio il proprio potenziale. Ma perché cambiare è così difficile?', category: 'Leadership', date: '31 maggio 2025', iso: '2025-05-31', img: '/blog/leadership-personale-il-potere-di-cambiare.jpg' },
  { slug: 'un-traguardo-per-pochi', title: 'Un traguardo per pochi', excerpt: 'Diventare coach è alla portata di tutti, ma al traguardo arriva solo chi si prepara e persevera. Le domande da porsi e i criteri per scegliere la formazione giusta.', category: 'Diventare coach', date: '5 agosto 2025', iso: '2025-08-05', img: '/blog/un-traguardo-per-pochi.jpg' },
  { slug: 'coaching-e-consapevolezza', title: 'Coaching e consapevolezza', excerpt: 'In che modo coaching e consapevolezza sono legati? Attraverso la metafora dell\'iceberg, un\'esplorazione di come mindset e paure guidano i comportamenti individuali e organizzativi, e di come l\'autoconsapevolezza libera il potenziale.', category: 'Leadership', date: '24 maggio 2025', iso: '2025-05-24', img: '/blog/coaching-e-consapevolezza.png' },
  { slug: 'alla-ricerca-della-felicita', title: 'Alla ricerca della felicità', excerpt: 'Cosa succede quando un coachee porta in sessione un obiettivo come “essere felice”? Una riflessione sulla misurabilità della felicità e su come, spesso, lo siamo già più di quanto pensiamo.', category: 'Crescita personale', date: '2 settembre 2025', iso: '2025-09-02', img: '/blog/alla-ricerca-della-felicita.png' },
  { slug: '11-consigli-notorieta-coaching', title: '11 consigli se sei in cerca di notorietà', excerpt: 'Undici spunti per chi vuole farsi conoscere come coach senza perdere di vista competenza, etica ed equilibrio personale.', category: 'Professione coach', date: '15 luglio 2025', iso: '2025-07-15', img: '/blog/11-consigli-notorieta-coaching.jpg' },
  { slug: 'euristiche-e-bias-cognitivi', title: 'Euristiche e bias cognitivi', excerpt: 'Le euristiche sono scorciatoie mentali che il cervello usa per risparmiare energia; i bias sono euristiche inappropriate. Perché riconoscerli è fondamentale nella pratica del coaching.', category: 'Intelligenza emotiva', date: '13 settembre 2025', iso: '2025-09-13', img: '/blog/euristiche-e-bias-cognitivi.jpg' },
  { slug: 'coaching-e-creativita', title: 'Coaching e creatività', excerpt: 'La creatività non è una dote per pochi eccentrici, ma un potenziale di ogni persona. Il confine tra creatività e reattività e come il coaching aiuta a scegliere consapevolmente come vivere ogni esperienza.', category: 'Metodo e pratica', date: '21 giugno 2025', iso: '2025-06-21', img: '/blog/coaching-e-creativita.jpg' },
  { slug: 'tutto-cio-che-ci-irrita-negli-altri-puo-portarci-a-capire-noi-stessi', title: '“Tutto ciò che ci irrita negli altri, può portarci a capire noi stessi”', excerpt: 'Quando un cliente ci irrita profondamente, spesso è un campanello d’allarme che parla di noi. Proiezioni, giudizio e self kindness: cosa i comportamenti che non sopportiamo negli altri rivelano di noi stessi.', category: 'Intelligenza emotiva', date: '9 settembre 2025', iso: '2025-09-09', img: '/blog/tutto-cio-che-ci-irrita-negli-altri-puo-portarci-a-capire-noi-stessi.jpg' },
  { slug: 'coaching-bene-comune', title: 'Coaching e bene comune', excerpt: 'Il coaching aiuta le persone a conoscere se stesse e ad agire in modo consapevole. Attraverso l\'esempio dell\'imbarco dei passeggeri, come il fattore umano cambia la percezione del bene comune.', category: 'Metodo e pratica', date: '10 giugno 2025', iso: '2025-06-10', img: '/blog/coaching-bene-comune.jpg' },
  { slug: 'trovare-clienti-come-coach', title: '5 consigli per trovare clienti come Coach', excerpt: 'Cinque idee concrete per costruire la propria professione di coach e trovare clienti, tra qualità, passaparola e promozione.', category: 'Professione coach', date: '5 luglio 2025', iso: '2025-07-05', img: '/blog/trovare-clienti-come-coach.jpg' },
  { slug: 'musica-e-cambiamento', title: 'Come la musica racconta il cambiamento', excerpt: 'Il cambiamento come una forza di gravità che ci attrae inevitabilmente. Una riflessione, da coach e da musicista, su come la vera trasformazione non venga dall’esterno ma da dentro di noi.', category: 'Crescita personale', date: '30 agosto 2025', iso: '2025-08-30', img: '/blog/musica-e-cambiamento.png' },
  { slug: 'presence-leadership', title: 'Il potere della Presenza nella leadership', excerpt: 'Cosa distingue i grandi leader? Una qualità che possiamo chiamare Presenza: l\'essere pienamente qui e ora, e come coltivarla con intenzione e consapevolezza.', category: 'Leadership', date: '20 maggio 2025', iso: '2025-05-20', img: '/blog/presence-leadership.png' },
  { slug: 'team-coaching-e-team-coaching-sistemico', title: 'Team Coaching e Team Coaching sistemico', excerpt: 'Team building, facilitazione, training e team coaching: attività diverse per lo sviluppo dei team. Perché l\'approccio sistemico è il più potente per una vera trasformazione.', category: 'Team coaching', date: '4 ottobre 2025', iso: '2025-10-04', img: '/blog/team-coaching-e-team-coaching-sistemico.jpg' },
  { slug: 'perche-diventare-coach', title: 'Perché diventare coach: chi sceglie questa strada', excerpt: 'Chi decide di diventare coach e perché: il ritratto di chi arriva a questa professione dopo altre carriere, e come capire se è la strada giusta anche per te.', category: 'Diventare coach', date: '17 giugno 2025', iso: '2025-06-17', img: '/blog/perche-diventare-coach-2.jpg' },
  { slug: 'sfide-adattive-cambiamento', title: 'Sfide adattive: pronti al cambiamento?', excerpt: 'Perché le organizzazioni falliscono quando affrontano con soluzioni tecniche sfide che sono in realtà adattive, e come i leader possono attraversare la trasformazione personale e collettiva necessaria.', category: 'Leadership', date: '17 maggio 2025', iso: '2025-05-17', img: '/blog/sfide-adattive-cambiamento.jpg' },
  { slug: 'il-grande-omuncolo', title: 'Il grande omuncolo', excerpt: 'Il valore di un professionista si misura nel suo essere umano: una riflessione su cosa distingue i veri coach dai \"Dr. Me\".', category: 'Crescita personale', date: '1 luglio 2025', iso: '2025-07-01', img: '/blog/il-grande-omuncolo.jpg' },
  { slug: 'dire-coach', title: 'Si fa presto a dire coach!', excerpt: 'Un modello per profilare i coach, il \"Conch\", che li colloca su due assi, quello del denaro e quello dei valori, delineando quattro profili tipici. Uno strumento di riflessione per capire chi sei come coach e dove vorresti andare.', category: 'Professione coach', date: '28 giugno 2025', iso: '2025-06-28', img: '/blog/dire-coach.jpg' },
  { slug: 'massimo-bene-comune-2', title: 'Il massimo bene comune', excerpt: 'Cos\'è davvero il bene comune? Una riflessione che attraversa storia, principio del Tao ed equilibrio dei sistemi per esplorare un concetto tanto ineffabile quanto necessario.', category: 'Metodo e pratica', date: '3 giugno 2025', iso: '2025-06-03', img: '/blog/massimo-bene-comune-2.jpg' },
  { slug: 'meditazione-e-coaching', title: 'Come Meditazione e Mindfulness aiutano nel coaching', excerpt: 'Concedersi dieci minuti di meditazione prima di ogni sessione per centrarsi ed entrare nel flow. Perché la pratica della presenza e del non giudizio allena le abilità fondamentali di ogni coach.', category: 'Intelligenza emotiva', date: '6 settembre 2025', iso: '2025-09-06', img: '/blog/meditazione-e-coaching.jpg' },
  { slug: 'supervision-icf-e-coaching', title: 'Supervision ICF e Coaching', excerpt: 'Che cos\'è la Supervisione nel coaching, in che modo si distingue dal Mentor Coaching e quale valore offre al coach professionista, ai suoi clienti e all\'integrità della professione.', category: 'Credenziali ICF', date: '27 maggio 2025', iso: '2025-05-27', img: '/blog/supervision-icf-e-coaching.png' },
  { slug: 'pensiero-sistemico-coaching', title: 'Pensiero sistemico e coaching', excerpt: 'Anche il bene comune sottostà alle leggi sistemiche. Perché coinvolgere tutte le parti e lasciare la responsabilità delle soluzioni ai clienti rende gli obiettivi più duraturi e sostenibili.', category: 'Team coaching', date: '14 giugno 2025', iso: '2025-06-14', img: '/blog/pensiero-sistemico-coaching.jpg' },
];

export const BLOG_BY_SLUG: Record<string, BlogMeta> = Object.fromEntries(
  BLOG_INDEX.map((p) => [p.slug, p]),
);
